spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}