server:
  port: 9000
  context-path: /comments

endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true

spring:
  config:
    name: comment-service
  application:
    name: comment-service
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=Mysql
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
