server:
  port: 9000
  context-path: /comments
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
spring:
   config:
      name:  comment-service
   application:
      name:  comment-service

