version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  eureka-service:
    build: eureka-service

  edge-service:
    build: edge-service
    ports:
      - 4444:4444

  web-service:
    build: web-service

  client-service:
      build: client-service

  monitoring:
    build: monitoring