version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sergiojf/nuntius-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  eureka-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sergiojf/nuntius-eureka-service
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: sergiojf/nuntius-gateway-service
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sergiojf/nuntius-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sergiojf/nuntius-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sergiojf/nuntius-account-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

  account-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: sergiojf/nuntius-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    

