server:
  port: 9100
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
spring:
  config:
    name: client-service
  application:
    name: client-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      failFast: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=Mysql
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
