
spring:
  application:
    name: monitoring
  config:
    name: monitoring
security:
  ignored: true
turbine:
  aggregator:
    clusterNameExpression: 'default'
  appConfig: comment-service,client-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}