server:
  port: 9999

endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
spring:
  config:
    name: web-service
  application:
    name: web-service


edge-service:
  ribbon:
    listOfServers: http://edge-service:4444

    # the eureka vipAddress of the target service (Disabled)
    #DeploymentContextBasedVipAddresses: samplebackendservice

    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 1

    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 1

    # Whether all operations can be retried for this client
    OkToRetryOnAllOperations: true

    # Interval to refresh the server list from the source
    ServerListRefreshInterval: 2000

    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000

    # Read timeout used by Apache HttpClient
    ReadTimeout: 3000